export const language = {
    En: {
        username: "Username",
        password: "Password",
        signIn: "Sign In",
        usersControl: "Users control",
        requests: "Requests",
        logout: "Logout",
        nameTable: "Name",
        roles: "Roles",
        actions: "Actions",
        edit: "Edit",
        resetPassword: "Reset password",
        add: "Add",
        search: "Search",
        saveChanges: "Save changes",
        cancel: "Cancel",
        addUser: "Add user",
        editUser: "Edit user",
        firstName: "First name",
        lastName: "Last name",
    },
    Ru: {
        username: "Имя пользователя",
        password: "Пароль",
        signIn: "Войти",
        usersControl: "Пользователи",
        requests: "Запросы",
        logout: "Выйти",
        nameTable: "Имя Фамилия",
        roles: "Роли",
        actions: "Действия",
        edit: "Изменить",
        resetPassword: "Сбросить пароль",
        add: "Добавить",
        search: "Поиск",
        saveChanges: "Сохранить",
        cancel: "Отмена",
        addUser: "Добавить пользователя",
        editUser: "Изменить пользователя",
        firstName: "Имя",
        lastName: "Фамилия",
    }
}