export const language = {
    En: {
        userName: "Username",
        password: "Password",
        signIn: "Sign In",
        usersControl: "Users control",
        requests: "Requests",
        logout: "Logout",
        nameTable: "Name",
        roles: "Roles",
        actions: "Actions",
        edit: "Edit",
        resetPassword: "Reset password",
        add: "Add",
        search: "Search",
        saveChanges: "Save changes",
        cancel: "Cancel",
        addUser: "Add user",
        editUser: "Edit user",
        firstName: "First name",
        lastName: "Last name",
        confirmPassword: "Confirm password",
        devices: "Devices",
        deviceName: "Device Name",
        registrationDate: "Registration date",
        decommissionDate: "Decommission date",
        assignedTo: "Assigned to",
        selectUser: "Select user",
        downloadQR: "Download QR code",
        changeDeviceName: "Change Device Name",
        makeInactive: "Make inactive",
        restore: "Restore",
        showInactiveUsers: "Show inactive users",
        showDecommissionDevices: "Show decommission devices",
        addDevice: "Add device",
    },
    Ru: {
        userName: "Имя пользователя",
        password: "Пароль",
        signIn: "Войти",
        usersControl: "Пользователи",
        requests: "Запросы",
        logout: "Выйти",
        nameTable: "Имя Фамилия",
        roles: "Роли",
        actions: "Действия",
        edit: "Изменить",
        resetPassword: "Сбросить пароль",
        add: "Добавить",
        search: "Поиск",
        saveChanges: "Сохранить",
        cancel: "Отмена",
        addUser: "Добавить пользователя",
        editUser: "Изменить пользователя",
        firstName: "Имя",
        lastName: "Фамилия",
        confirmPassword: "Подтвердите пароль",
        devices: "Устройства",
        deviceName: "Имя устройства",
        registrationDate: "Дата регистрации",
        decommissionDate: "Дата списания",
        assignedTo: "Пользователь",
        selectUser: "Выбрать пользователя",
        downloadQR: "Скачать QR код",
        changeDeviceName: "Изменить имя устройства",
        makeInactive: "Сделать неактивным",
        restore: "Восстановить",
        showInactiveUsers: "Показать неактивных пользователей",
        showDecommissionDevices: "Показать списанные устройства",
        addDevice: "Добавить устройство",
    }
}